package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@RestController
@RequestMapping(path="/Users")

public class UserRepoController {
    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    
    //Usage: curl -X POST http://localhost:8080/Users -d '{"name": "Kalyan", "email":"Kalyan@gmail.com"}' -H "Content-Type: application/json"
    //Usage: curl -X POST http://localhost:8080/Users -d '{"name": "Chintalapati", "email":"Chintalapati@gmail.com"}' -H "Content-Type: application/json"
    
    @PostMapping(path="")
    public @ResponseBody String addNewUser (@RequestBody User user) 
		{
        User newUser = new User();
        newUser.setName(user.getName());
        newUser.setEmail(user.getEmail());
        userRepository.save(newUser);
        return "User: " + newUser.getName() + " Saved Sucessfully\n";
    }
		
		
		//Usage: curl http://localhost:8080/Users/all
		
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() 
		{
        return userRepository.findAll();
    }

    
    //Usage: curl http://localhost:8080/Users?id=1
    @GetMapping(path="")
    public @ResponseBody User getUser(@RequestParam Long id) 
		{
        return userRepository.findOne(id);
    }

    
    //Usage: curl -X DELETE "http://localhost:8080/Users?id=1"
    @DeleteMapping(path="")
    public @ResponseBody String deleteUser(@RequestParam Long id) 
		{
        userRepository.delete(id);
        return "User-Id:" + id + " Deleted successfully\n";
    }
}